import { 
  PiPants,
  PiTShirt,
  PiShirtFolded,
  PiSock,
  PiBed,
  PiHand,
  PiSoccerBall,
  PiCamera,
  PiBook,
  PiHeadphones,
  PiLaptop,
  PiWatch,
  PiBaseballCap,
  PiSquare,
  PiCube,
  PiSwimmingPool,
  PiSneaker,
  PiBelt,
} from 'react-icons/pi';
import { GiMonclerJacket, GiUnderwearShorts, GiShorts } from 'react-icons/gi';

export const iconMap: { [key: string]: React.ComponentType } = {
  'PiPants': PiPants,
  'PiTShirt': PiTShirt,
  'PiShirtFolded': PiShirtFolded,
  'PiSock': PiSock,
  'PiSquare': PiSquare,
  'PiBed': PiBed,
  'PiBaseballCap': PiBaseballCap,
  'PiHand': PiHand,
  'PiSoccerBall': PiSoccerBall,
  'GiUnderwearShorts': GiUnderwearShorts,
  'PiCamera': PiCamera,
  'PiBook': PiBook,
  'PiHeadphones': PiHeadphones,
  'PiLaptop': PiLaptop,
  'PiWatch': PiWatch,
  'PiSwimming': PiSwimmingPool,
  'PiSneaker': PiSneaker,
  'PiBelt': PiBelt,
  'GiMonclerJacket': GiMonclerJacket,
  'PiCoat': GiMonclerJacket,
  'PiCube': PiCube, // Default icon if not found
  'GiShorts': GiShorts,
};
